# Generated by Django 5.0.6 on 2024-06-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_geeksmodel_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='date_created',
        ),
    ]
